### ISSUE TITLE
Longer API calls fail

### ISSUE THREAD

**Issue by tashrifbillah** [nutterb/redcapAPI#10]
I notice that longer API calls have been disconnecting. Our project has ~2,500 variables. A record JSON is ~6 MB. When I try to upload the record to REDCap using API, REDCap disconnects yielding the following error:
```bash
Traceback (most recent call last):
  File "/miniconda3/envs/dpimport/lib/python3.10/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/miniconda3/envs/dpimport/lib/python3.10/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/miniconda3/envs/dpimport/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/miniconda3/envs/dpimport/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/miniconda3/envs/dpimport/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/miniconda3/envs/dpimport/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/miniconda3/envs/dpimport/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/miniconda3/envs/dpimport/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/miniconda3/envs/dpimport/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/miniconda3/envs/dpimport/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

I have found that some smaller forms upload successfully. But breaking the above record down to smaller forms does not work for us as we have multiple large forms e.g. PSYCHS, SCID-5, and FIGS.

What do you think I can do to remedy the above?

**Comment by nutterb** [comment]
Potentially resolved via https://github.com/vubiostat/redcapAPI/pull/64. If problems persist, please submit a new issue to the vubiostat repository.
